#Configuration for the websocket server.
spectator:
  #Logs to the console (0 = off, 1 = simple, 2 = verbose).
  logging: 0
  #Determines if the connection should be kept alive.
  keepConnectionAlive: false
  camera:
    x: 0
    y: 0
    z: 0
    range:
      x: 4
      y: 4
      z: 4